version: '3'

services:
  mysql:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: people_db
      MYSQL_ALLOW_EMPTY_PASSWORD: false
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  nodejs:
    build: 
      context: nodejs
    working_dir: /app
    volumes:
      - ./nodejs:/app
    command: bash -c "npm install && node server.js"
    environment:
      - DB_HOST=mysql
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=people_db
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs